# https://github.com/release-drafter/release-drafter/blob/v5.3.1/.github/release-drafter.yml
name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
template: |
  # What's Changed

  $CHANGES
categories:
  - title: "🚀 Features"
    labels:
      - add
  - title: "🐛 Bug Fixes"
    labels:
      - fix
  - title: "♻️ Maintenance"
    labels:
      - update
