name: On commit hook

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          # https://github.com/actions/setup-node/issues/32#issuecomment-1003854758
          node-version-file: '.nvmrc'
      - name: prepare dependencies
        run: |
          npm install
          npm install -g pnpm@7.1.5
      - name: test
        run: pnpm run precommit
