name: Publish to npm

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          # https://github.com/actions/setup-node/issues/32#issuecomment-1003854758
          node-version-file: '.nvmrc'
      - name: prepare dependencies
        run: npm install
      - name: test
        run: npm run precommit
      - name: publish
        run: |
          echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' >> .npmrc
          echo 'registry=https://registry.npmjs.org/' >> .npmrc
          echo 'always-auth=true' >> .npmrc
          npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
